name: Debian Builder
on: [push,workflow_dispatch]
jobs:
  debian_builder:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    permissions:
      contents: write # release changes require contents write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: |
          cd .devel
          chmod +x build_container.sh && ./build_container.sh
      - name: Extract debian files
        run: |
          cd .devel
          chmod +x build_container.sh && ./extract_debian_from_container.sh

