name: Debian Builder
on: [push,workflow_dispatch]

jobs:
  debian_builder:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: |
          cd .devel
          chmod +x build_container.sh && ./build_container.sh
      - name: Extract debian files
        run: |
          cd .devel
          chmod +x build_container.sh && ./extract_debian_from_container.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.os }}
          path: .devel/upload/*

  build_ppa:
    needs: debian_builder

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4 # Download all artifacts
        with:
          path: ppa/
          merge-multiple: true
      - name: Create package files # https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
        run: |
          cd ppa
          ls -lah
          echo -e "$PGP_PRIVATE_KEY" | gpg --import
          gpg --armor --export "murilomarinho@ieee.org" > KEY.gpg
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          sudo apt-get install apt-utils tree
          apt-ftparchive release . > Release
          gpg --default-key "murilomarinho@ieee.org" -abs -o - Release > Release.gpg
          gpg --default-key "murilomarinho@ieee.org" --clearsign -o - Release > InRelease
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/smartarmstack_lgpl.gpg] https://smartarmstack.github.io/smart_arm_stack_ROS2 ./" > smartarmstack_lgpl.list
          ls -lah
      - name: Upload PPA Files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ppa/*

  deploy_page:
    needs: build_ppa

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4