# https://github.com/ros-tooling/setup-ros
name: Debian Builder # On Linux, iterates on all ROS 1 and ROS 2 distributions.
on: [push,workflow_dispatch]
jobs:
  test_docker: # On Linux, iterates on all ROS 1 and ROS 2 distributions.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build image
        run: |
          cd .devel
          chmod +x build_container.sh && ./build_container.sh