name: sas isolated package build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: build
        run: |
          cd docker
          docker compose build

      - name: test
        run: |
          cd docker
          docker compose up    
